### ISSUE TITLE
Clarification about expected running time

### ISSUE THREAD

**Issue by mathcass** [philiptromans/mapswipe-ml-dataset-generator#3]
First off, thanks for the work on this @philiptromans. This is very useful. 

I wanted to open an issue for discussion on expected running time for this. We can close it afterward. 

I've tried running this command: 

    ./generate_dataset.py 6807 --bing-maps-key <bing-maps-key> -o laos

and I haven't had it finished at all so I haven't built a dataset successfully at all. Sometimes it just takes a very long time and sometimes I get a socket error because of a connection issue. 

Here's my question: for a download that you ran earlier, how long did it take to build a dataset? If it takes a very long time, we might want to add some logging to account for this or notify the script caller. 

---

Here's some simple `print` debugging that I added to look at this: 

* https://github.com/mathcass/mapswipe-ml-dataset-generator/commit/521a3824f19acac203aa45483514d958d4fcd54a

**Comment by philiptromans** [comment]
Has it made any progress at all? It starts off by downloading the json file, so you should see it in ~/.mapswipe/&lt;project id&gt;/project_details.json
It'll never do this again though, so that stays cached forever.

Then, it goes and tries to compute a list of all the tiles in the project perimeter. Some of these are bigger than others, and it took my (admittedly fairly new laptop) up to maybe 10 minutes to do some of the projects. Admittedly 6807 is one of the biggest ones. Maybe try 7049 first, just to check everything's ok? Again, this gets cached so you should see a file in ~/.mapswipe/&lt;project_id&gt;/all_tiles.pickled , and the next time it starts loading the file should be very quick.

After that it'll start generating a dataset. The dataset I'm currently generating still isn't finished, but it doesn't really *need* to finish per se. Everything's output as it goes along (and all tile images get cached, so if you re-run it the dataset gets generated almost instantly, or at least up to where you finished last time) and the dataset is usable at any moment during the generation, it just gets bigger the longer you leave it running (although once it can't find any more tiles it'll stop).

Anyway, let me know how far it's getting and we can see. It does output a status as it downloads tiles though. Do you have output that looks something like this?

> phil@vimes:~/missingmaps$ ./generate_dataset.py 6807 6794 6930 7064 7125 6918 7049 --bing-maps-key blah -o laos
> Directory laos already exists. Delete? [y/N] y
> Preselecting tiles from project (#6807)... 
> Preselecting tiles from project (#6794)... 
> Preselecting tiles from project (#6930)... 
> Preselecting tiles from project (#7064)... 
> Preselecting tiles from project (#7125)... 
> Preselecting tiles from project (#6918)... 
> Preselecting tiles from project (#7049)... 
> Tiles picked: test: 7547, train: 60371, valid: 7546 in each of ['built', 'bad_imagery', 'empty']
>

**Comment by mathcass** [comment]
Hi @philiptromans, thanks for this. This is helpful. Hearing that it took around 10 minutes helps give me some context on this. 

I had gotten output like you've shown, but have in a few instances gotten a socket error (`connection refused`). 

So far, I've had it running for roughly for about 10 minutes tonight and I've only gotten a total of 107 tiles downloaded. 

    ./generate_dataset.py 7049 --bing-maps-key $BING_KEY -o laos
    
    ... Most of the time spent in between here is sleeping while reaching out to the Bing API
    
    Tiles picked: test: 13, train: 102, valid: 13 in each of ['built', 'bad_imagery', 'empty']
    ^C

so at this point I think that it's downloading tiles a bit more slowly than I expected it to.

**Comment by philiptromans** [comment]
One thing to note is that it's actually downloaded (13 + 102 +13) * 3 = 384
tiles. I guess I need to make the output clearer, but that's what I mean
when I say in *each of* ['built', ...]. I think that's about right for 10
mins (600 seconds) and 50000 tiles / day (0.58 tiles / second).

I'll work on trying to give better progress numbers soon.

I occasionally get I/O problems, but they're relatively rare. I'll stick
some retry logic in there at some point as well.

On 10 Aug 2017 4:04 am, "Cass" <notifications@github.com> wrote:

Hi @philiptromans <https://github.com/philiptromans>, thanks for this. This
is helpful. Hearing that it took around 10 minutes helps give me some
context on this.

I had gotten output like you've shown, but have in a few instances gotten a
socket error (connection refused).

So far, I've had it running for roughly for about 10 minutes tonight and
I've only gotten a total of 107 tiles downloaded.

./generate_dataset.py 7049 --bing-maps-key $BING_KEY -o laos

... Most of the time spent in between here is sleeping while reaching
out to the Bing API

Tiles picked: test: 13, train: 102, valid: 13 in each of ['built',
'bad_imagery', 'empty']
^C

so at this point I think that it's downloading tiles a bit more slowly than
I expected it to.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/philiptromans/mapswipe-ml-dataset-generator/issues/3#issuecomment-321437987>,
or mute the thread

**Comment by mathcass** [comment]
Sorry for the late reply Philip (#lifeproblems), but I think I got this working correctly and I have a good idea now on the expected running time. 

Cheers,
Cass
